# Changes here will be overwritten by Copier
_commit: v2.0.2
_src_path: gh:lincc-frameworks/python-project-template
author_email: loredo@astro.cornell.edu
author_name: Tom Loredo
create_example_module: true
custom_install: true
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: skymapuq
project_license: MIT
project_name: skymapuq
project_organization: tloredo
python_versions:
- '3.10'
- '3.11'
